import { DesignTokens } from './types';

export interface PresetTheme {
  id: string;
  name: string;
  category: string;
  description: string;
  tokens: DesignTokens;
}

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'salud-clinico',
    name: 'Salud y Ciencias Médicas',
    category: 'Salud / Clínico',
    description: 'Tonos azul sanitario, cian y superficies claras de alta limpieza visual. Ideal para protocolos clínicos, enfermería y farmacología.',
    tokens: {
      name: 'Salud y Ciencias Médicas',
      description: 'Estilo aséptico, profesional y de máxima legibilidad con acentos de verificación médica.',
      bg: '#f8fafc',
      surface: '#ffffff',
      surfaceSubtle: '#f0fdfa',
      inkPrimary: '#0f172a',
      inkMuted: '#475569',
      accentPrimary: '#0284c7',
      accentSecondary: '#0d9488',
      fontTitle: 'Outfit',
      fontBody: 'Plus Jakarta Sans',
      radiusSm: '6px',
      radiusMd: '12px',
      radiusLg: '18px',
      shadowSm: '0 1px 3px rgba(15, 23, 42, 0.06)',
      shadowMd: '0 4px 14px rgba(2, 132, 199, 0.08)',
      characteristicElement: 'orbital',
    },
  },
  {
    id: 'academico-formal',
    name: 'Académico Universitario',
    category: 'Humanidades / Derecho',
    description: 'Azul marino de cátedra con acentos dorados y fondo marfil sutil. Inspirado en publicaciones universitarias y normativas legales.',
    tokens: {
      name: 'Académico Universitario',
      description: 'Elegancia institucional, encuadre normativo riguroso y calidez de lectura prolongada.',
      bg: '#fafaf9',
      surface: '#ffffff',
      surfaceSubtle: '#f5f5f4',
      inkPrimary: '#1c1917',
      inkMuted: '#57534e',
      accentPrimary: '#1e3a8a',
      accentSecondary: '#b45309',
      fontTitle: 'Cinzel',
      fontBody: 'Lora',
      radiusSm: '4px',
      radiusMd: '8px',
      radiusLg: '14px',
      shadowSm: '0 1px 3px rgba(28, 25, 23, 0.05)',
      shadowMd: '0 6px 18px rgba(30, 58, 138, 0.07)',
      characteristicElement: 'sidebar',
    },
  },
  {
    id: 'edtech-moderno',
    name: 'Innovación & EdTech',
    category: 'Tecnología / STEM',
    description: 'Índigo digital, violeta y contrastes vibrantes con tarjetas flotantes. Diseñado para cursos de programación, datos e innovación.',
    tokens: {
      name: 'Innovación & EdTech',
      description: 'Aspecto contemporáneo, dinámico y modular que estimula el aprendizaje activo.',
      bg: '#f8faff',
      surface: '#ffffff',
      surfaceSubtle: '#eef2ff',
      inkPrimary: '#111827',
      inkMuted: '#4b5563',
      accentPrimary: '#4f46e5',
      accentSecondary: '#06b6d4',
      fontTitle: 'Space Grotesk',
      fontBody: 'Inter',
      radiusSm: '8px',
      radiusMd: '14px',
      radiusLg: '22px',
      shadowSm: '0 2px 4px rgba(79, 70, 229, 0.05)',
      shadowMd: '0 10px 25px rgba(79, 70, 229, 0.1)',
      characteristicElement: 'rail',
    },
  },
  {
    id: 'minimalista-editorial',
    name: 'Minimalismo Editorial',
    category: 'Pedagógico General',
    description: 'Equilibrio escandinavo, tipografía sans-serif refinada, bordes suaves y máximo espacio en blanco para reducir la carga cognitiva.',
    tokens: {
      name: 'Minimalismo Editorial',
      description: 'Limpio y atemporal, enfocado 100% en la claridad conceptual.',
      bg: '#ffffff',
      surface: '#f9fafb',
      surfaceSubtle: '#f3f4f6',
      inkPrimary: '#111827',
      inkMuted: '#6b7280',
      accentPrimary: '#2563eb',
      accentSecondary: '#64748b',
      fontTitle: 'Plus Jakarta Sans',
      fontBody: 'Inter',
      radiusSm: '6px',
      radiusMd: '12px',
      radiusLg: '16px',
      shadowSm: '0 1px 2px rgba(0, 0, 0, 0.04)',
      shadowMd: '0 4px 12px rgba(0, 0, 0, 0.05)',
      characteristicElement: 'pill',
    },
  },
  {
    id: 'verde-ambiental',
    name: 'Bio, Ambiente & Agro',
    category: 'Ciencias Naturales',
    description: 'Verde esmeralda profundo, salvia y tonos tierra sutiles para contenidos de ecología, biotecnología y gestión ambiental.',
    tokens: {
      name: 'Bio, Ambiente & Agro',
      description: 'Armonía orgánica con alto contraste accesible para diagramas y procesos de campo.',
      bg: '#fbfcfb',
      surface: '#ffffff',
      surfaceSubtle: '#f0fdf4',
      inkPrimary: '#14301e',
      inkMuted: '#3f5647',
      accentPrimary: '#15803d',
      accentSecondary: '#0f766e',
      fontTitle: 'Montserrat',
      fontBody: 'Open Sans',
      radiusSm: '6px',
      radiusMd: '12px',
      radiusLg: '20px',
      shadowSm: '0 1px 3px rgba(20, 48, 30, 0.05)',
      shadowMd: '0 6px 16px rgba(21, 128, 61, 0.08)',
      characteristicElement: 'orbital',
    },
  },
];
